# Use root/example as user/password credentials
version: '3.1'

services:
  redis:
    image: redis
    ports:
      - 8001:6379
    volumes:
      - /redis/data:/data
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./Mongo/sampledata.archive.gz:/tmp/sampledata.archive.gz
      - ./Mongo/data:/data/db
    #command: bash -c "mongorestore --username root --password example --gzip --archive=/tmp/sampledata.archive.gz"      
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      RABBITMQ_ERLANG_COOKIE: secret_cookie
  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 9000:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
  registry:
    tty: true
    build:                #Add to adjust the error: Service api has neither an image nor a build context specified. At least one must be provided.
      context: ./ServiceRegistry
      dockerfile: Dockerfile.dev
    ports:
      - 8002:8000
    volumes:
      - /app/target
      - ./ServiceRegistry/src:/app/src
  config-server:
    tty: true
    build:                #Add to adjust the error: Service api has neither an image nor a build context specified. At least one must be provided.
      context: ./configServer
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - /app/target
      - ./configServer/src:/app/src
  gateway:
    tty: true
    build:                #Add to adjust the error: Service api has neither an image nor a build context specified. At least one must be provided.
      context: ./gateway
      dockerfile: Dockerfile.dev
    ports:
      - 8003:8000
    volumes:
      - ./gateway/src:/app/src
  admin:
    tty: true
    build:                #Add to adjust the error: Service api has neither an image nor a build context specified. At least one must be provided.
      context: ./admin 
      dockerfile: Dockerfile.dev     
    ports:
      - 8004:8000
    volumes:
      - ./admin/src:/app/src
  product-catalog:
    tty: true
    build:                #Add to adjust the error: Service api has neither an image nor a build context specified. At least one must be provided.
      context: ./ProductCataLogService 
      dockerfile: Dockerfile.dev     
    depends_on:
      - mongo
      - admin
      - registry
      - rabbitmq
      - gateway
    #ports:
    #  - 7000:8000
    volumes:
      - ./ProductCataLogService/src:/app/src
  price:
    tty: true
    build:                #Add to adjust the error: Service api has neither an image nor a build context specified. At least one must be provided.
      context: ./Price 
      dockerfile: Dockerfile.dev     
    depends_on:
      - mongo
      - admin
      - registry
      - rabbitmq
      - gateway
    ports:
      - 7001:8000
    volumes:
      - ./Price/src:/app/src
  cart:
    tty: true
    build:                #Add to adjust the error: Service api has neither an image nor a build context specified. At least one must be provided.
      context: ./CartService 
      dockerfile: Dockerfile.dev     
    depends_on:
      - mongo
      - admin
      - registry
      - rabbitmq
      - gateway
    ports:
      - 7002:8000
    volumes:
      - ./CartService/src:/app/src
  order:
    tty: true
    build:                #Add to adjust the error: Service api has neither an image nor a build context specified. At least one must be provided.
      context: ./OrderService 
      dockerfile: Dockerfile.dev     
    ports:
      - 7003:8000
    volumes:
      - ./OrderService/src:/app/src
  front-end:
    tty: true
    build:                #Add to adjust the error: Service api has neither an image nor a build context specified. At least one must be provided.
      context: ./front-end 
      dockerfile: Dockerfile.dev     
    depends_on:
      - admin
      - registry
      - gateway
    ports:
      - 3000:3000
    volumes:
      - ./front-end:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    volumes:
        - ./rabbitmq/etc/:/etc/rabbitmq/
        - ./rabbitmq/logs/:/var/log/rabbitmq/
    ports:
        - 5672:5672
        - 5671:5671
        - 25672:25672
        - 4369:4369
        - 15671:15671
        - 15672:15672