hibernate:
  ogm:
    datastore:
      create_database: true
      database: priceAssignment
      host: localhost
      password: example
      port: 27017
      provider: mongodb
      username: root
    mongodb:
      authentication_database: admin
server:
  port: 6001

spring:
  application:
    name: price-service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8002/eureka/}   
      
microservices:
  endpoints:
    endpoint:
      productCatalog:
        products: "localhost:6000"