   
server:
  port: 8000
  

spring:
  application:
    name: gateway-service
   
#hystrix.command.default.execution.timeout.enabled
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false