spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/prasunmax/cloud-config-server
server:
  port: 8000

management:
  security:
    enabled: false 
  